FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04


RUN chsh -s /bin/bash
SHELL ["/bin/bash", "-c"]

RUN apt-get update &&\
    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion && \
    apt-get clean

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh  -O /tmp/miniconda.sh && \
  /bin/bash /tmp/miniconda.sh -b -p /opt/conda && \
  rm /tmp/miniconda.sh && \
  echo "export PATH=/opt/conda/bin:$PATH" > /etc/profile.d/conda.sh
ENV PATH /opt/conda/bin:$PATH

RUN conda config --set remote_read_timeout_secs 300
RUN conda create -y --solver=libmamba -n rapids-23.12 -c rapidsai -c conda-forge -c nvidia  \
    rapids=23.12 python=3.10 cuda-version=11.8


RUN conda run -n rapids-23.12 pip install torch torchvision torchaudio\
	--index-url https://download.pytorch.org/whl/cu118
RUN conda run -n rapids-23.12 pip install torch_geometric pyg_lib\
	torch_scatter torch_sparse torch_cluster torch_spline_conv\
	-f https://data.pyg.org/whl/torch-2.2.0+cu118.html

ENV CONDA_DEFAULT_ENV rapids-23.12
RUN conda init
RUN echo "conda activate rapids-23.12" >> /root/.bashrc
