FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion && apt-get clean && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p /opt/conda && rm /tmp/miniconda.sh && \
    /opt/conda/bin/conda clean -af

RUN /opt/conda/bin/conda config --set remote_read_timeout_secs 300

RUN /opt/conda/bin/conda create -y --solver=libmamba -n env -c rapidsai -c conda-forge -c nvidia rapids=23.12 python=3.10 cuda-version=11.8 && \
    /opt/conda/bin/conda clean -af

RUN conda run -n env pip install torch torchvision torchaudio\
	--index-url https://download.pytorch.org/whl/cu118
RUN conda run -n env pip install torch_geometric pyg_lib\
	torch_scatter torch_sparse torch_cluster torch_spline_conv\
	-f https://data.pyg.org/whl/torch-2.2.0+cu118.html


ENV CONDA_DEFAULT_ENV env
ENV PATH /opt/conda/envs/env/bin:$PATH
RUN conda init && \
    echo "conda activate rapids-23.12" >> /root/.bashrc
